klimaosveta/urls.py
from django.contrib import admin
from django.urls import include, path
from webapp.views import Home, CourseListView, LectorListView, AboutView, RegionView, ConfirmEmailView, RegionDetailView, CourseRegisterView, FinalCourseView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', Home.as_view(), name='home'),
    path('kurzy/', CourseListView.as_view(), name='courses'),
    path('lektori/', LectorListView.as_view(), name='lectors'),
    path('o-projektu/', AboutView.as_view(), name='about'),
    path('kraje/', RegionView.as_view(), name='regions'),
    path('confirm-email/<uuid:confirmation_code>/', ConfirmEmailView.as_view(), name='confirm_email'),
    path('kurzy/<slug:slug>/', RegionDetailView.as_view(), name='region-detail'),
    path('prihlaseni-na-kurz/<int:pk>/', CourseRegisterView.as_view(), name='register_course'),
    path('zaverecny-kurz', FinalCourseView.as_view(), name='final_course')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/models.py
from django.db import models
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit
import uuid

class BasicSite(models.Model):
    name = models.CharField()
    title = models.CharField()
    html = models.TextField()



class Message(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Jméno")
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Zpráva")
    procesed = models.BooleanField(default=False)



class Course(models.Model):
    headline = models.CharField()
    html = models.TextField()
    shortcut = models.CharField(max_length=1, unique=True)
    image_on_left = models.BooleanField(default=False)
    order = models.PositiveSmallIntegerField(default=1)
    image = models.ImageField(upload_to='courses_img')
    image_optimal = ImageSpecField(
        source='image',
        processors=[ResizeToFit(1920, 100000)],
        format='JPEG',
        options={'quality': 80}
    )
    program = models.FileField(upload_to='program/')

    def __str__(self):
        return f'{self.shortcut} - {self.headline}'

    class Meta:
        verbose_name = "Typ kurzu"  # Lidsky čitelný název pro jednotný objekt
        verbose_name_plural = "Typy kurzů"  # Lidsky čitelný název pro množný počet objektů
        ordering = ['order']  # Objekty budou ve výchozím stavu řazeny podle 'order'



class Lector(models.Model):
    name = models.CharField(max_length=255, verbose_name="Jméno")
    about = models.TextField(verbose_name="Text o sobě")
    image = models.ImageField(upload_to='lektori_obrazky/', verbose_name="Obrázek")
    image_optimal = ImageSpecField(source='image',
        processors=[ResizeToFit(800, 10000)],  # Použití ResizeToFit
        format='JPEG',
        options={'quality': 80}
    )

    image_admin = ImageSpecField(source='image',
        processors=[ResizeToFit(150, 10000)],  # Použití ResizeToFit
        format='JPEG',
        options={'quality': 50}
    )

    order = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Lektor"
        verbose_name_plural = "Lektoři"


class Region(models.Model):
    name = models.CharField(max_length=255, verbose_name="Název kraje")
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "kraj"
        verbose_name_plural = "kraje"

class CourseDetail(models.Model):
    region = models.ForeignKey('Region', on_delete=models.CASCADE, verbose_name="Kraj")
    date = models.DateField(verbose_name="Datum kurzu")
    course = models.ForeignKey('Course', on_delete=models.CASCADE, verbose_name="Kurz")
    lector = models.ForeignKey('Lector', on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Lektor")
    max_capacity = models.PositiveIntegerField(verbose_name="Maximální kapacita")
    current_capacity = models.PositiveIntegerField(verbose_name="Aktuální obsazenost")
    spaces = models.CharField(verbose_name="Prostory", null=True, blank=True)

    def __str__(self):
        return f"{self.region.name} - {self.date}"


    def is_full(self):
        """Vrátí True, pokud je kurz plně obsazen, jinak False."""
        return self.current_capacity >= self.max_capacity

    def available_seats(self):
        """Vrátí počet dostupných míst."""
        return self.max_capacity - self.current_capacity

    class Meta:
        verbose_name = "Jednotlivý kurz"
        verbose_name_plural = "Jednotlivé kurzy"
        ordering = ['date']

class CourseParticipant(models.Model):
    course_detail = models.ForeignKey('CourseDetail', on_delete=models.CASCADE, verbose_name="Kurz")
    first_name = models.CharField(max_length=255, verbose_name="Jméno")
    last_name = models.CharField(max_length=255, verbose_name="Příjmení")
    email = models.EmailField(verbose_name="E-mail")
    phone = models.CharField(max_length=255, verbose_name="Telefon")
    confirmation_code = models.UUIDField(default=uuid.uuid4, editable=False)
    confirmation_code_expires = models.DateTimeField(null=True, blank=True)
    confirm = models.BooleanField(default=True, verbose_name="Potvrzeno")
    note = models.TextField(null=True, blank=True, verbose_name="Poznámka")

    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.course_detail.region}"

    class Meta:
        verbose_name = "Účastník kurzu"
        verbose_name_plural = "Účastníci kurzu"


class FinalCourseParticipant(models.Model):
    first_name = models.CharField(max_length=255, verbose_name="Jméno")
    last_name = models.CharField(max_length=255, verbose_name="Příjmení")
    email = models.EmailField(verbose_name="E-mail")
    phone = models.CharField(max_length=255, verbose_name="Telefon")
    note = models.TextField(null=True, blank=True, verbose_name="Poznámka")
    day_1 = models.BooleanField(default=True, verbose_name="Termín 25.9.")
    day_2 = models.BooleanField(default=True, verbose_name="Termín 26.9.")

    class Meta:
        verbose_name = "Účastník závěrečného kurzu"
        verbose_name_plural = "Účastnici závěrečného kurzu"
        ordering = ['last_name', 'first_name']

webapp/forms.py
from django import forms
from webapp.models import Message, CourseParticipant, FinalCourseParticipant


class ContactForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Jméno', 'label': ''}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email', 'label': ''}),
            'message': forms.Textarea(attrs={'placeholder': 'Zpráva', 'label': ''}),
        }
        labels = {
            'name': '',
            'email': '',
            'message': '',
        }


class CourseParticipantForm(forms.ModelForm):
    class Meta:
        model = CourseParticipant
        fields = ['first_name', 'last_name', 'email', 'phone', 'note',]

        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'Jméno', 'label': ''}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Příjmení', 'label': ''}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email', 'label': ''}),
            'phone': forms.NumberInput(attrs={'placeholder': 'Telefonní číslo', 'label': ''}),
            'note': forms.Textarea(attrs={'placeholder': 'Poznámka', 'label': ''}),
        }

class FinalCourseParticipantForm(forms.ModelForm):
    class Meta:
        model = FinalCourseParticipant
        fields = ['first_name', 'last_name', 'email', 'phone', 'note', 'day_1', 'day_2',]

        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'Jméno', 'label': ''}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Příjmení', 'label': ''}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email', 'label': ''}),
            'phone': forms.NumberInput(attrs={'placeholder': 'Telefonní číslo', 'label': ''}),
            'note': forms.Textarea(attrs={'placeholder': 'Poznámka', 'label': ''}),
            'day_1': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'day_2': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

webapp/views.py
from django.views.generic import TemplateView, ListView, DetailView, View
from django.shortcuts import redirect
from webapp.models import BasicSite, Course, Lector, CourseParticipant, Region, CourseDetail
from webapp.forms import ContactForm, CourseParticipantForm, FinalCourseParticipantForm
from django.shortcuts import get_object_or_404, render
from django.utils.timezone import now


class Home(TemplateView):
    template_name = 'webapp/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = BasicSite.objects.get(name='home')
        context['form'] = ContactForm()
        return context

    def post(self, request, *args, **kwargs):
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')

        return self.render_to_response(self.get_context_data(form=form))

class RegionView(TemplateView):
    template_name = 'webapp/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = BasicSite.objects.get(name='region')
        context['form'] = ContactForm()
        return context

    def post(self, request, *args, **kwargs):
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')

        return self.render_to_response(self.get_context_data(form=form))


class AboutView(DetailView):
    model = BasicSite
    template_name = 'webapp/about.html'
    context_object_name = 'basic_site'

    def get_object(self):
        return get_object_or_404(BasicSite, name='about')


class CourseListView(ListView):
    model = Course
    template_name = 'webapp/courses.html'
    context_object_name = 'courses'

    def get_queryset(self):
        return Course.objects.all().order_by('order')


class LectorListView(ListView):
    model = Lector
    template_name = 'webapp/lectors.html'
    context_object_name = 'lectors'

    def get_queryset(self):
        return Lector.objects.all().order_by('order')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['basic_site'] = BasicSite.objects.get(name='lectors')
        return context

class ConfirmEmailView(View):
    def get(self, request, *args, **kwargs):
        confirmation_code = kwargs.get('confirmation_code')
        participant = get_object_or_404(CourseParticipant, confirmation_code=confirmation_code, confirm=False, confirmation_code_expires__gte=now())
        participant.confirm = True
        participant.save()
        return render(request, 'webapp/course_finish.html', {'participant': participant})

class RegionDetailView(DetailView):
    model = Region
    template_name = 'webapp/region_detail.html'
    context_object_name = 'region'
    slug_url_kwarg = 'slug'
    query_pk_and_slug = True


class CourseRegisterView(View):
    form_class = CourseParticipantForm
    template_name = 'webapp/course_register.html'  # Aktualizujte cestu k šabloně

    def get(self, request, *args, **kwargs):
        course_detail = get_object_or_404(CourseDetail, pk=kwargs['pk'])
        form = self.form_class()
        return render(request, self.template_name, {'form': form, 'course_detail': course_detail})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            participant = form.save(commit=False)
            participant.course_detail = get_object_or_404(CourseDetail, pk=kwargs['pk'])
            participant.save()
            return render(request, 'webapp/course_confirm.html', {'participant': participant})
        return render(request, self.template_name, {'form': form, 'course': course.participant.course_detail})


class FinalCourseView(View):
    form_class = FinalCourseParticipantForm
    template_name = 'webapp/final_course_register.html'

    def get(self, request, *args, **kwargs):
            form = self.form_class()
            return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            participant = form.save(commit=False)
            participant.save()
            return render(request, 'webapp/final_course_finish.html', {'participant': participant})
        return render(request, self.template_name, {'form': form})

webapp/templates/webapp/about.html
{% extends 'webapp/base.html' %}

{% block title %}{{ basic_site.title }}{% endblock %}

{% block content %}

{{ basic_site.html|safe }}


{% endblock %}

webapp/templates/webapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'webapp/styles.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <title>{% block title %}{% endblock title %}</title>
</head>
<body>

{% block content %}
{% endblock content %}

</body>
</html>

webapp/templates/webapp/course_confirm.html
{% extends 'webapp/base.html' %}

{% block title %}{% endblock %}

{% block content %}


{% comment %}
<div class="section center">
    <h1>Registrace na kurz &lsquo;{{ participant.course_detail.course.headline }}&rsquo; pro {{ participant.course_detail.region }}.</h1>

    <p>Na Vámi zadanou emailovou adresu byl odeslán ověřovací email, který prosím potvrďte.</p>

     <a href="{% url 'home' %}" class="basicbutton bluebutton">Zpět na titulní stránku</a>

</div>

{% endcomment %}

<div class="section center">
    <h1>Byl jste přihlášen na kurz:</h1>

<h2>{{ participant.course_detail.course.headline }}&rsquo; pro {{ participant.course_detail.region }}.</h1></h2>
<h2>V termínu {{ participant.course_detail.course.date }}, 09:00 – 15:00</h2>

    <p>Děkujeme.</p>

     <a href="{% url 'home' %}" class="basicbutton bluebutton">Zpět na titulní stránku</a>

</div>





{% endblock %}

webapp/templates/webapp/course_finish.html
{% extends 'webapp/base.html' %}

{% block title %}{% endblock %}

{% block content %}



<div class="section center">
    <h1>Byl jste přihlášen na kurz:</h1>

<h2>{{ course.course.headline }} pro {{ course.region }}</h2>
<h2>V termínu {{ course.date }}, 09:00 – 15:00</h2>

    <p>Děkujeme.</p>

     <a href="{% url 'home' %}" class="basicbutton bluebutton">Zpět na titulní stránku</a>

</div>





{% endblock %}

webapp/templates/webapp/course_register.html
{% extends 'webapp/base.html' %}

{% block title %}{% endblock %}

{% block content %}



<div class="section center">
<h1>Přihlášení na kurz</h1>
<h2>{{ course_detail.course.headline }} pro {{ course_detail.region }}</h2>
<h2>V termínu {{ course_detail.date }}, 09:00 – 15:00</h2>
<div class="contact-form">
<form id="contact-form" method="post">
    {% csrf_token %}
    <div class="form-field">
      {{ form.first_name }}
    </div>
    <div class="form-field">
      {{ form.last_name }}
    </div>
    <div class="form-field">
      {{ form.email }}
    </div>
    <div class="form-field">
      {{ form.phone }}
    </div>
      <div class="form-field">
      {{ form.note }}
    </div>

    <button class="basicbutton graybutton" type="submit">Odeslat</button>
</form>
</div>

{% comment %}
<div class="section center margintop-10">
   <p>Po odeslání formuláře dostanete ověřovací email, který potvrďte.</p>
</div>
{% endcomment %}




{% endblock %}

webapp/templates/webapp/final_course_finish.html
{% extends 'webapp/base.html' %}

{% block title %}{% endblock %}

{% block content %}



<div class="section center">
    <h1>Byl jste přihlášen na závěrečný kurz.</h1>

<h2>Klima? Bez vody a vegetace to nepůjde!</h2>
<h2>V termínu 25-26.9. 2025</h2>

    <p>Děkujeme.</p>

     <a href="{% url 'home' %}" class="basicbutton bluebutton">Zpět na titulní stránku</a>

</div>





{% endblock %}

webapp/templates/webapp/final_course_register.html
{% extends 'webapp/base.html' %}

{% block title %}{% endblock %}

{% block content %}



<div class="section center">
<h1>Přihlášení na závěrečný kurz</h1>
<h2>Závěrečný kurz pro projekt: Klima? Bez vody a vegetace to nepůjde!</h2>
<h2>Termín:
</h2>
    <ul><li>25.9.2025 Přednášky</li><li>26.9.2025 Terénní exkurze</li></ul><br />

<p>Pokud se nemůžete zúčastnit kurzů v plnném rozsahu, označtě to prosím ve spodní části formuláře.</p><br />
    <h2>
        V prostorách ENKI o.p.s., Dukelská 145, Třeboň<br />
        (Závěrečný kurz je zdarma.)
    </h2>
<div class="contact-form">
<form id="contact-form" method="post">
    {% csrf_token %}
    <div class="form-field">
      {{ form.first_name }}
    </div>
    <div class="form-field">
      {{ form.last_name }}
    </div>
    <div class="form-field">
      {{ form.email }}
    </div>
    <div class="form-field">
      {{ form.phone }}
    </div>
      <div class="form-field">
      {{ form.note }}
    </div>

  <table style="width: 100%; border-collapse: collapse;">
    <tr>
        <td style="font-size: 20px; font-weight: bold; color: #333; padding: 10px; text-align: right;">
            Zúčastním se termínu: 25.9. (Přednášky)
        </td>
        <td style="padding: 10px; text-align: left;">
            {{ form.day_1 }}
        </td>
    </tr>
    <tr>
        <td style="font-size: 20px; font-weight: bold; color: #333; padding: 10px; text-align: right;">
            Zúčastním se termínu: 26.9. (Exkurze)
        </td>
        <td style="padding: 10px; text-align: left;">
            {{ form.day_2 }}
        </td>
    </tr>
</table>





    <button class="basicbutton graybutton" type="submit">Odeslat</button>
</form>
</div>

{% comment %}
<div class="section center margintop-10">
   <p>Po odeslání formuláře dostanete ověřovací email, který potvrďte.</p>
</div>
{% endcomment %}


</div>

{% endblock %}

webapp/templates/webapp/home.html
{% extends 'webapp/base.html' %}

{% block title %}{{ page.title }}{% endblock %}

{% block content %}


{{ page.html|safe }}

{% endblock %}

webapp/templates/webapp/lectors.html
{% extends 'webapp/base.html' %}

{% block title %}{{ basic_site.title }}{% endblock %}

{% block content %}

{{ basic_site.html|safe }}

{% for lector in lectors %}
<div class="section center margintop10">
    <div class="lector-content">
        {% if lector.image_optimal %}
            <div class="lector-image">
                <img src="{{ lector.image_optimal.url }}" alt="{{ lector.name }}" style="width: 100%; height: auto;">
            </div>
        {% endif %}
        <div class="lector-text">
            <h3>{{ lector.name }}</h3>
            {{ lector.about|safe }}
        </div>
    </div>

</div>
{% endfor %}



{% endblock %}

webapp/templates/webapp/region_detail.html
{% extends 'webapp/base.html' %}

{% block title %}Termíny kurzů pro {{ region.name }}{% endblock %}

{% block content %}

<div class="section center">
    <h1>Termíny kurzů pro {{ region.name }}</h1>




  <div class="link-container region_detail">
  {% for course_detail in region.coursedetail_set.all %}
      <div class="link-lecture">
          <h2>{{ course_detail.course.headline }}</h2>
          <p>{{ course_detail.date }}</p>
          <p>09:00 – 15:00</p>
          <p><a href="{{ course_detail.course.program.url }}">Program ke stažení (pdf)</a></p>
          <p class="adress">{% if course_detail.spaces %}{{ course_detail.spaces|safe }}{% endif %}</p>
          {% if course_detail.is_full %}
             <p>Kurz je plně obsazen.</p>
          {% else %}
             <p>K dispozici je {{ course_detail.available_seats }} míst z celkových {{ course_detail.max_capacity }}.</p>
        {% endif %}


          <a href="{% url 'register_course' course_detail.pk %}">
              <img src="{{ course_detail.course.image_optimal.url }}" alt="">
              <p><button class="basicbutton bluebutton">Registrace na kurz</button></p>
          </a>
          <p class="space">{% if not course_detail.spaces %}V současné době ještě není zajištěn prostor<br /> pro realizaci semináře.<br /> Jakmile bude prostor zajištěn, <br />bude Vám adresa konání zaslána<br /> na Vaši mailovou adresu.{% endif %}</p>
      </div>
{% empty %}
    <p>V tomto kraji nyní nejsou plánovány žádné kurzy.</p>
      {% endfor %}




</div>



{% endblock %}